// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SerbleAPI.Models;

#nullable disable

namespace SerbleAPI.Migrations
{
    [DbContext(typeof(SerbleDbContext))]
    [Migration("20260623115444_AddBalancesApiKeysAndDateCreated")]
    partial class AddBalancesApiKeysAndDateCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SerbleAPI.Models.DbApp", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("AccessPolicy")
                        .HasColumnType("int");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublicClient")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("OidcRedirectUris")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("RequirePkce")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("RequiredPermLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbAppApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("AppApiKeys");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbAppGroupClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("GroupId");

                    b.ToTable("AppGroupClaims");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbAppGroupRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("Deny")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("GroupId");

                    b.ToTable("AppGroupRules");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbBalance", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<ulong>("Coins")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("OwnerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbKv", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Key");

                    b.ToTable("Kvs");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbOidcAuthorizationCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("AuthTimeUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CodeChallenge")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("CodeChallengeMethod")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("Consumed")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("ExpiresAtUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("Nonce")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Code");

                    b.ToTable("OidcAuthorizationCodes");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbOidcRefreshGrant", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("AuthTimeUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("ExpiresAtUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("GrantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Rotated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("TokenHash");

                    b.ToTable("OidcRefreshGrants");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbOwnedProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("User");

                    b.ToTable("OwnedProducts");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbSerbleProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("AllowAnonymous")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<bool>("IsSubscription")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("PriceIdsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PriceLookupIdsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Purchasable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SuccessRedirect")
                        .HasColumnType("longtext");

                    b.Property<string>("SuccessTokenSecret")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Webhook")
                        .HasColumnType("longtext");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("SerbleProducts");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbServiceCatalogItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("New")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VisibilityMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceCatalogItems");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbServiceCatalogItemGroupRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceCatalogItemGroupRules");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Password")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("PermLevel")
                        .HasColumnType("int");

                    b.Property<int>("PremiumLevel")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("TotpEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("VerifiedEmail")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserAuthorizedApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAuthorizedApps");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserNote", b =>
                {
                    b.Property<string>("NoteId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("NoteId");

                    b.HasIndex("User");

                    b.ToTable("UserNotes");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserPasskey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AaGuid")
                        .HasColumnType("longtext");

                    b.Property<string>("AttesClientDataJson")
                        .HasColumnType("longtext");

                    b.Property<string>("AttesFormat")
                        .HasColumnType("longtext");

                    b.Property<string>("AttesObject")
                        .HasColumnType("longtext");

                    b.Property<bool?>("BackedUp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("BackupEligible")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CredentialId")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptorId")
                        .HasColumnType("longtext");

                    b.Property<int?>("DescriptorTransports")
                        .HasColumnType("int");

                    b.Property<int?>("DescriptorType")
                        .HasColumnType("int");

                    b.Property<string>("DevicePublicKeys")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PublicKey")
                        .HasColumnType("longtext");

                    b.Property<int?>("SignCount")
                        .HasColumnType("int");

                    b.Property<int?>("Transports")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("UserPasskeys");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbApp", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbUser", "OwnerNavigation")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbAppApiKey", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbApp", "AppNavigation")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbAppGroupClaim", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbApp", "AppNavigation")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleAPI.Models.DbGroup", "GroupNavigation")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppNavigation");

                    b.Navigation("GroupNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbAppGroupRule", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbApp", "AppNavigation")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleAPI.Models.DbGroup", "GroupNavigation")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppNavigation");

                    b.Navigation("GroupNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbOwnedProduct", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbServiceCatalogItemGroupRule", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbGroup", "GroupNavigation")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleAPI.Models.DbServiceCatalogItem", "ServiceNavigation")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupNavigation");

                    b.Navigation("ServiceNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserAuthorizedApp", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbApp", "AppNavigation")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleAPI.Models.DbUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserGroup", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbGroup", "GroupNavigation")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleAPI.Models.DbUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserNote", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserPasskey", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbUser", "OwnerNavigation")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
