// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SerbleAPI.Models;

#nullable disable

namespace SerbleAPI.Migrations
{
    [DbContext(typeof(SerbleDbContext))]
    partial class SerbleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SerbleAPI.Models.DbApp", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbKv", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Key");

                    b.ToTable("Kvs");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbOwnedProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("User");

                    b.ToTable("OwnedProducts");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Password")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("PermLevel")
                        .HasColumnType("int");

                    b.Property<int>("PremiumLevel")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("TotpEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("VerifiedEmail")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserAuthorizedApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAuthorizedApps");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserNote", b =>
                {
                    b.Property<string>("NoteId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("NoteId");

                    b.HasIndex("User");

                    b.ToTable("UserNotes");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserPasskey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AaGuid")
                        .HasColumnType("longtext");

                    b.Property<string>("AttesClientDataJson")
                        .HasColumnType("longtext");

                    b.Property<string>("AttesFormat")
                        .HasColumnType("longtext");

                    b.Property<string>("AttesObject")
                        .HasColumnType("longtext");

                    b.Property<bool?>("BackedUp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("BackupEligible")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CredentialId")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptorId")
                        .HasColumnType("longtext");

                    b.Property<int?>("DescriptorTransports")
                        .HasColumnType("int");

                    b.Property<int?>("DescriptorType")
                        .HasColumnType("int");

                    b.Property<string>("DevicePublicKeys")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PublicKey")
                        .HasColumnType("longtext");

                    b.Property<int?>("SignCount")
                        .HasColumnType("int");

                    b.Property<int?>("Transports")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("UserPasskeys");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbApp", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbUser", "OwnerNavigation")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbOwnedProduct", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserAuthorizedApp", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbApp", "AppNavigation")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleAPI.Models.DbUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserNote", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleAPI.Models.DbUserPasskey", b =>
                {
                    b.HasOne("SerbleAPI.Models.DbUser", "OwnerNavigation")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
